extends Resource


const DEFAULT: Dictionary = {
	"BOT_RADIUS": 32,
	"SHIELD_CAP": 20,
	"SHIELD_RECOVERY": 1,
	"HEALTH_CAP": 20,
	"SPEED": 1200,
	"KNOCBACK_RESIST": 0.5,
	"TRANSFORM_SPEED": 0.7,
	"CHARGE_COOLDOWN": 3,
	"CHARGE_FORCE_FACTOR": 0.5,
	"CHARGE_CRIT_MULT": 2,
	"CHARGE_CRIT_CHANCE": 0.2,
	"CHARGE_DAMAGE_RATE": 0.3,
	"DESTRUCTIBLE": false,
	"FACTION": Color(1,0,0,1),
	"CHARGE_OUTLINE": Color(1,0,0.9,1)
}
